# Generated by Django 4.0.6 on 2022-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
    ]
